components:
  - name: return 
    params:
      config:
        name: return
    type: dataqa.components.gather.GatherOutput
    input_source:
      rewritten_query: query_rewriter.rewritten_query
      code: code_generator.code
      execution_output: code_executor

  - name: gpt_4o_model
    params:
      model: gpt-4o-2024-08-06
      api_version: "2024-08-01-preview"
      api_type: "azure_ad"
      temperature: 0
      num_response: 1
      max_response_token: 2000
    type: dataqa.llm.openai.AzureOpenAI

  - name: query_rewriter
    params:
      llm: COMP_gpt_4o_model
      config:
        name: query_rewriter
        model: gpt-4o-2024-08-06
        prompt: FILE_{BASE_DIR}/examples/cib_mp/data/rewriter_prompt.txt
        input: 
        - name: query
          type: str
          description: input query
        - name: previous_rewritten_query
          type: str
          description: a list of messages in the conversation history
        output:
        - name: rewritten_query
          type: str
          description: the rewritten query after considering the conversation history
        - name: rewriter_reasoning
          type: str
          description: the reasoning procedure for generating the rewritten query
    type: dataqa.components.llm_component.base_prompt_llm_chain.BasePromptLLMChain
    input_source:
      query: START.query
      previous_rewritten_query: START.previous_rewritten_query

  - name: code_generator_prompt
    params:
      config:
        name: code_generator_prompt
        prompt: FILE_{BASE_DIR}/examples/cib_mp/data/code_prompt.txt
        input: 
        - name: rewritten_query
          type: str
          description: input query
    type: dataqa.components.prompt.base_prompt.BasePrompt
    input_source:
      rewritten_query: query_rewriter.rewritten_query

  - name: code_generator
    description: Run the code generator prompt
    params:
      llm: COMP_gpt_4o_model
      config:
        name: code_generator
        output:
        - name: code
          type: str
          description: the generated code
        - name: reasoning
          type: str
          description: the reasoning procedure for generating code
        output_parser: xml
    type: dataqa.components.llm_component.base_llm_component.BaseLLMComponent
    input_source:
      messages: code_generator_prompt.messages

  - name: code_executor
    params:
      config:
        name: code_executor
        component_type: in_memory_executor
        data_files: 
        - path: "{BASE_DIR}/examples/cib_mp/data/fake_PROD_BD_TH_FLAT_V3.csv"
          table_name: PROD_BD_TH_FLAT_V3
        - path: "{BASE_DIR}/examples/cib_mp/data/fake_EIS_D_CUST_PORTFOLIO.csv"
          table_name: EIS_D_CUST_PORTFOLIO
        input:
        - name: code
          type: str
          description: generated code
    type: dataqa.components.code_executor.in_memory_code_executor.InMemoryCodeExecutor
    input_source:
      code: code_generator.code

pipelines:
  - name: cib_mp_pipeline
    nodes:
      - name: query_rewriter
        parent_groups:
          - parent: START
      - name: code_generator_prompt
        parent_groups:
          - parent: query_rewriter
      - name: code_generator
        parent_groups:
          - parent: code_generator_prompt
      - name: code_executor
        parent_groups:
          - parent: code_generator
      - name: return
        parent_groups:
          - parent: code_executor
      - name: END
        parent_groups:
          - parent: return
