repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: [--fix, --select, "I"]
      - id: ruff-format
        types_or: [ python, pyi ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        exclude: mkdocs.yml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict