# Basic DataQA Agent Configuration
# Minimal configuration for getting started with DataQA

name: "basic-data-agent"
description: "Simple agent for basic data queries and analysis"
version: "1.0.0"

# LLM Configuration - OpenAI GPT-3.5 for cost-effective queries
llm:
  provider: "openai"
  model: "gpt-3.5-turbo"
  api_key: "${OPENAI_API_KEY}"
  temperature: 0.1
  max_tokens: 1000

# Knowledge Base - Simple in-memory storage
knowledge:
  provider: "faiss"
  embedding_model: "all-MiniLM-L6-v2"
  top_k: 3

# Executor - Basic in-memory execution
executor:
  provider: "inmemory"
  database_type: "duckdb"
  max_execution_time: 30.0

# Workflow - Simple workflow with approval
workflow:
  strategy: "react"
  require_approval: true
  enable_visualization: true

# Logging
log_level: "INFO"