# Development DataQA Agent Configuration
# Configuration optimized for development and testing

name: "dev-data-agent"
description: "Development agent with debugging and testing features"
version: "1.0.0"

# LLM Configuration - Fast model for development
llm:
  provider: "openai"
  model: "gpt-3.5-turbo"
  api_key: "${OPENAI_API_KEY}"
  temperature: 0.2  # Slightly higher for variety during testing
  max_tokens: 1500
  timeout: 30.0
  max_retries: 2

# Knowledge Base - Fast local storage
knowledge:
  provider: "faiss"
  embedding_model: "all-MiniLM-L6-v2"  # Fast, lightweight model
  chunk_size: 256  # Smaller chunks for faster processing
  chunk_overlap: 25
  top_k: 5
  similarity_threshold: 0.6  # Lower threshold for more results

# Executor - Permissive settings for development
executor:
  provider: "inmemory"
  database_type: "duckdb"
  max_execution_time: 60.0
  max_memory_mb: 1024
  max_rows: 10000
  
  # Development-friendly settings
  allow_file_access: true  # Allow file operations for testing
  allowed_imports:
    - "pandas"
    - "numpy"
    - "matplotlib"
    - "seaborn"
    - "datetime"
    - "math"
    - "statistics"
    - "json"
    - "csv"
    - "pathlib"
  blocked_functions:
    - "exec"
    - "eval"
    - "__import__"
    - "compile"

# Workflow - Development-optimized workflow
workflow:
  strategy: "react"
  max_iterations: 5  # Fewer iterations for faster testing
  require_approval: false  # Auto-approve for development
  auto_approve_safe: true
  conversation_memory: true
  max_context_length: 4000
  enable_visualization: true
  debug_mode: true  # Enable debug output

# Verbose logging for development
log_level: "DEBUG"
data_dir: "./dev_data"
cache_dir: "./dev_cache"

# Development-specific configuration
extra_config:
  development:
    mock_llm: false  # Set to true to use mock responses
    save_conversations: true
    export_debug_info: true
  testing:
    generate_test_data: true
    validate_outputs: true
  features:
    experimental_features: true
    beta_features: true