# Enterprise DataQA Agent Configuration
# Production-ready configuration with enhanced security and performance

name: "enterprise-data-agent"
description: "Enterprise-grade agent with advanced security and monitoring"
version: "1.0.0"

# LLM Configuration - GPT-4 for high-quality responses
llm:
  provider: "openai"
  model: "gpt-4"
  api_key: "${OPENAI_API_KEY}"
  temperature: 0.05  # Lower temperature for consistency
  max_tokens: 2000
  timeout: 60.0
  max_retries: 5
  extra_params:
    frequency_penalty: 0.1
    presence_penalty: 0.1

# Knowledge Base - OpenSearch for production scale
knowledge:
  provider: "opensearch"  # Use OpenSearch for enterprise deployment
  embedding_model: "all-mpnet-base-v2"  # Higher quality embeddings
  chunk_size: 1024
  chunk_overlap: 100
  top_k: 10
  similarity_threshold: 0.8
  
  # OpenSearch configuration
  opensearch_host: "${OPENSEARCH_HOST}"
  opensearch_port: 9200
  opensearch_username: "${OPENSEARCH_USERNAME}"
  opensearch_password: "${OPENSEARCH_PASSWORD}"
  opensearch_index: "dataqa-enterprise-knowledge"
  opensearch_ssl: true
  opensearch_verify_certs: true

# Executor - API-based execution for security
executor:
  provider: "api"  # Remote execution for security
  api_url: "${EXECUTOR_API_URL}"
  api_key: "${EXECUTOR_API_KEY}"
  max_execution_time: 120.0
  max_memory_mb: 2048
  max_rows: 100000
  
  # Enhanced security settings
  allow_file_access: false
  allowed_imports:
    - "pandas"
    - "numpy"
    - "matplotlib"
    - "seaborn"
    - "datetime"
    - "math"
    - "statistics"
    - "scipy"
  blocked_functions:
    - "exec"
    - "eval"
    - "open"
    - "__import__"
    - "compile"
    - "subprocess"
    - "os"
    - "sys"

# Workflow - Advanced workflow with strict approval
workflow:
  strategy: "plan_execute"  # More sophisticated planning
  max_iterations: 20
  require_approval: true
  auto_approve_safe: false  # Always require approval
  conversation_memory: true
  max_context_length: 8000
  enable_visualization: true
  debug_mode: false

# Enhanced logging and monitoring
log_level: "INFO"
data_dir: "${DATA_DIR}"
cache_dir: "${CACHE_DIR}"

# Enterprise-specific configuration
extra_config:
  security:
    audit_logging: true
    data_masking: true
    pii_detection: true
  monitoring:
    metrics_enabled: true
    tracing_enabled: true
    health_check_interval: 300
  compliance:
    data_retention_days: 90
    encryption_at_rest: true
    encryption_in_transit: true