# Example DataQA Agent Configuration
# This file demonstrates the complete configuration schema for DataQA agents

name: "example-data-agent"
description: "Example configuration for a DataQA agent with comprehensive settings"
version: "1.0.0"

# LLM Configuration
llm:
  provider: "openai"  # openai, anthropic, local
  model: "gpt-4"
  api_key: "${OPENAI_API_KEY}"  # Environment variable substitution
  temperature: 0.1
  max_tokens: 2000
  timeout: 30.0
  max_retries: 3
  extra_params:
    frequency_penalty: 0.0
    presence_penalty: 0.0

# Knowledge Base Configuration  
knowledge:
  provider: "faiss"  # faiss, opensearch, memory
  embedding_model: "all-MiniLM-L6-v2"
  chunk_size: 512
  chunk_overlap: 50
  top_k: 5
  similarity_threshold: 0.7
  
  # OpenSearch settings (when provider is opensearch)
  # opensearch_host: "localhost"
  # opensearch_port: 9200
  # opensearch_username: "admin"
  # opensearch_password: "${OPENSEARCH_PASSWORD}"
  # opensearch_index: "dataqa-knowledge"

# Code Execution Configuration
executor:
  provider: "inmemory"  # inmemory, api, docker
  database_type: "duckdb"
  max_execution_time: 30.0
  max_memory_mb: 512
  max_rows: 10000
  
  # Security settings
  allow_file_access: false
  allowed_imports:
    - "pandas"
    - "numpy" 
    - "matplotlib"
    - "seaborn"
    - "datetime"
    - "math"
    - "statistics"
  blocked_functions:
    - "exec"
    - "eval"
    - "open"
    - "__import__"
    - "compile"
  
  # Database connection (optional)
  # database_url: "${DATABASE_URL}"
  
  # API executor settings (when provider is api)
  # api_url: "https://api.example.com/execute"
  # api_key: "${EXECUTOR_API_KEY}"

# Workflow Configuration
workflow:
  strategy: "react"  # react, workflow, plan_execute
  max_iterations: 10
  require_approval: true
  auto_approve_safe: false
  conversation_memory: true
  max_context_length: 4000
  enable_visualization: true
  debug_mode: false

# Global Settings
log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
data_dir: "./data"
cache_dir: "./cache"

# Additional custom configuration
extra_config:
  custom_prompts:
    system_prompt: "You are a helpful data analysis assistant."
  features:
    enable_sql_explain: true
    enable_code_review: true