use_case_config:
  - name: prime_equities
    cwd_config: "examples/prime_eq/agent/cwd_agent_prompt_template.yaml"
    test_data_file: "examples/prime_eq/examples.yml"
  - name: cib_gb
    cwd_config: "examples/gb/agent/cwd_agent_prompt_template.yaml"
    test_data_file: "examples/gb/examples_0626.yml"
  - name: cdao
    cwd_config: "examples/cdao_dia/agent/cwd_agent_prompt_template.yaml"
    test_data_file: "examples/cdao_dia/examples.yml"
  - name: cib_mp
    cwd_config: "examples/cib_mp/agent/cwd_agent_prompt_template.yaml"
    test_data_file: "examples/cib_mp/examples.yaml"
  - name: cib_tp
    cwd_config: "examples/cib_tp/agent/cwd_agent_prompt_template.yaml"
    test_data_file: "examples/cib_tp/examples.yaml"
output: "benchmark/output/agent_20250627_prompt_back"
log: "benchmark/log/agent_20250627_error_prompt_back"
run_id: 2
run_llm_eval: true
run_prediction: true
num_run: 5
llm_judge_model: "gpt-4.1-2025-04-14"
batch_size: 5
resume: true
debug: true
solution_type: agent
